# Generated by Django 4.2.7 on 2025-11-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_raffle_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='enable_referral',
            field=models.BooleanField(default=True, help_text='Permitir que clientes indiquem amigos', verbose_name='Ativar Indicações'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='referral_min_purchase',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade mínima de números para poder indicar (0 = sem mínimo)', verbose_name='Mínimo para Indicar'),
        ),
    ]
