# Generated by Django 4.2.7 on 2025-11-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0004_add_referral_code_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='invitee_min_purchase',
            field=models.PositiveIntegerField(default=5, help_text='Quantidade mínima que o indicado precisa comprar para ganhar o bônus', verbose_name='Compra Mínima do Indicado'),
        ),
    ]
