# Generated by Django 4.2.7 on 2025-11-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0005_raffle_invitee_min_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentagem de taxa sobre o valor (ex: 5.00 para 5%)', max_digits=5, verbose_name='Taxa (%)'),
        ),
    ]
