# Generated by Django 4.2.7 on 2025-11-10 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raffles', '0006_raffle_fee_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número Premiado')),
                ('prize_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Prêmio (R$)')),
                ('release_percentage_min', models.DecimalField(decimal_places=2, help_text='Ex: 18.00 para 18%', max_digits=5, verbose_name='Porcentagem Mínima (%)')),
                ('release_percentage_max', models.DecimalField(decimal_places=2, help_text='Ex: 22.00 para 22%', max_digits=5, verbose_name='Porcentagem Máxima (%)')),
                ('is_released', models.BooleanField(default=False, verbose_name='Foi Liberado')),
                ('is_won', models.BooleanField(default=False, verbose_name='Foi Ganho')),
                ('won_at', models.DateTimeField(blank=True, null=True, verbose_name='Ganho em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_numbers', to='raffles.raffle')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prize_numbers_won', to=settings.AUTH_USER_MODEL, verbose_name='Ganhador')),
            ],
            options={
                'verbose_name': 'Número Premiado',
                'verbose_name_plural': 'Números Premiados',
                'ordering': ['release_percentage_min', 'number'],
                'unique_together': {('raffle', 'number')},
            },
        ),
    ]
