# Generated by Django 4.2.7 on 2025-11-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0007_prizenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='enable_progressive_bonus',
            field=models.BooleanField(default=False, help_text='Indicador ganha números extras baseado na quantidade que o indicado compra', verbose_name='Ativar Bônus Progressivo'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='progressive_bonus_every',
            field=models.PositiveIntegerField(default=20, help_text='A cada X números que o indicado compra, o indicador ganha 1 número extra (ex: 20 = ganha 1 número a cada 20 comprados)', verbose_name='Bônus a Cada X Números'),
        ),
    ]
