# Generated by Django 4.2.7 on 2025-11-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0008_add_progressive_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='enable_milestone_bonus',
            field=models.BooleanField(default=False, help_text='Cliente ganha prêmio especial ao atingir quantidade mínima', verbose_name='Ativar Prêmio por Meta'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='enable_purchase_bonus',
            field=models.BooleanField(default=False, help_text='Cliente ganha números extras ao comprar quantidade específica', verbose_name='Ativar Bônus por Quantidade'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='milestone_prize_description',
            field=models.TextField(blank=True, help_text='Detalhes sobre o prêmio especial', verbose_name='Descrição do Prêmio'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='milestone_prize_name',
            field=models.CharField(blank=True, help_text='Ex: PDF Exclusivo, Curso Online, etc', max_length=200, verbose_name='Nome do Prêmio'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='milestone_quantity',
            field=models.PositiveIntegerField(default=50, help_text='Quantidade mínima de números para ganhar o prêmio', verbose_name='Quantidade Mínima'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='purchase_bonus_amount',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade de números grátis ganhos', verbose_name='Ganhe Y Números'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='purchase_bonus_every',
            field=models.PositiveIntegerField(default=10, help_text='A cada X números comprados, ganha Y números grátis', verbose_name='A Cada X Números'),
        ),
    ]
