# Generated by Django 4.2.7 on 2025-11-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0008_add_progressive_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='premium_numbers',
            field=models.JSONField(blank=True, default=dict, help_text='Números especiais com prêmios. Formato: {"número": {"prize": "Prêmio", "prize_value": 500}}', verbose_name='Cotas Premiadas'),
        ),
    ]
