# Generated by Django 4.2.7 on 2025-11-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0009_raffle_enable_milestone_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Logo principal do site (recomendado: 120x120px, PNG com fundo transparente)', null=True, upload_to='site_config/', verbose_name='Logo do Site')),
                ('logo_base64', models.TextField(blank=True, help_text='Logo codificada em base64 para uso em templates', verbose_name='Logo Base64')),
                ('site_name', models.CharField(default='Sistema de Rifas', help_text='Nome exibido no site', max_length=100, verbose_name='Nome do Site')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
