# Generated by Django 4.2.7 on 2025-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0009_raffle_enable_milestone_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_base64', models.TextField(blank=True, help_text='Logo em formato Base64. Cole o código data:image/... completo aqui.', verbose_name='Logo do Site (Base64)')),
                ('site_name', models.CharField(default='Sistema de Rifas', help_text='Nome exibido no site', max_length=100, verbose_name='Nome do Site')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
