# Generated by Django 4.2.7 on 2025-11-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0010_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rafflenumber',
            name='source',
            field=models.CharField(choices=[('purchase', 'Compra'), ('purchase_bonus', 'Bônus de Compra'), ('milestone_bonus', 'Bônus Milestone'), ('referral_inviter', 'Bonus Indicante'), ('referral_invitee', 'Bonus Indicado')], default='purchase', max_length=30, verbose_name='Origem'),
        ),
    ]
