# Generated by Django 4.2.7 on 2025-11-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0011_add_bonus_source_options'),
    ]

    operations = [
        # Add premium_numbers field as nullable (legacy/deprecated field)
        migrations.AddField(
            model_name='raffle',
            name='premium_numbers',
            field=models.PositiveIntegerField(blank=True, help_text='Campo legado - não utilizado', null=True, verbose_name='Números Premium (Deprecated)'),
        ),
    ]
