# Generated by Django 4.2.7 on 2025-11-12 16:54

from django.db import migrations


def make_premium_numbers_nullable(apps, schema_editor):
    """Make premium_numbers column nullable in PostgreSQL"""
    from django.db import connection

    with connection.cursor() as cursor:
        # Check if the column exists and if it's NOT NULL
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name, is_nullable
                FROM information_schema.columns
                WHERE table_name='raffles_raffle' AND column_name='premium_numbers';
            """)
            result = cursor.fetchone()

            if result and result[1] == 'NO':
                # Column exists and is NOT NULL, make it nullable
                cursor.execute("""
                    ALTER TABLE raffles_raffle
                    ALTER COLUMN premium_numbers DROP NOT NULL;
                """)
        elif connection.vendor == 'sqlite':
            # SQLite doesn't need this operation as the previous migration handles it
            pass


def reverse_make_premium_numbers_nullable(apps, schema_editor):
    """Reverse operation - do nothing as we want to keep the column nullable"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0012_remove_premium_numbers'),
    ]

    operations = [
        migrations.RunPython(
            make_premium_numbers_nullable,
            reverse_make_premium_numbers_nullable
        ),
    ]
