# Generated by Django 4.2.7 on 2025-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0013_make_premium_numbers_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='admin_phones',
            field=models.TextField(blank=True, help_text='Números de WhatsApp dos administradores, um por linha. Ex: 5511999999999', verbose_name='WhatsApp dos Admins'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='group_phones',
            field=models.TextField(blank=True, help_text='IDs dos grupos de WhatsApp, um por linha. Ex: 5511999999999-1234567890@g.us', verbose_name='WhatsApp dos Grupos'),
        ),
    ]
