# Generated by Django 4.2.7 on 2025-11-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0014_add_prize_notification_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='admin_whatsapp',
            field=models.CharField(blank=True, help_text='Número de WhatsApp para suporte (ex: 5511999999999). Se vazio, usará o padrão da configuração.', max_length=20, verbose_name='WhatsApp de Suporte'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='premium_numbers',
            field=models.PositiveIntegerField(blank=True, help_text='Campo legado - não utilizado', null=True, verbose_name='Números Premium (Deprecated)'),
        ),
    ]
