# Generated by Django 4.2.7 on 2025-11-14 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0017_fix_duplicate_premium_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='milestone_prize_file',
            field=models.FileField(blank=True, help_text='Upload do arquivo (PDF, ZIP, etc) para download', null=True, upload_to='milestone_rewards/', verbose_name='Arquivo do Prêmio (PDF, ZIP, etc)'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='milestone_prize_url',
            field=models.URLField(blank=True, help_text='Link externo para acesso ao prêmio digital (Google Drive, Dropbox, etc)', verbose_name='Link Digital do Prêmio'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='premium_numbers',
            field=models.PositiveIntegerField(blank=True, help_text='Campo legado - não utilizado', null=True, verbose_name='Números Premium (Deprecated)'),
        ),
    ]
