# Generated by Django 4.2.7 on 2025-11-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0018_raffle_milestone_prize_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='is_test_mode',
            field=models.BooleanField(default=False, help_text='Ativa pagamento teste para simular compras e testar notificações', verbose_name='Modo de Teste'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='premium_numbers',
            field=models.PositiveIntegerField(blank=True, help_text='Campo legado - não utilizado', null=True, verbose_name='Números Premium (Deprecated)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='home_redirect_raffle',
            field=models.ForeignKey(blank=True, help_text='Campanha para a qual a página inicial redirecionará. Se vazio, mostra lista de campanhas.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='raffles.raffle', verbose_name='Campanha Padrão da Home'),
        ),
    ]
