# Generated by Django 4.2.7 on 2025-11-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0021_add_reserved_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='admin_phones',
            field=models.TextField(blank=True, help_text='Números de WhatsApp dos administradores e/ou grupos de admin, um por linha. Receberão notificação COM dados do ganhador (WhatsApp, nome). Ex: 5511999999999 ou 120363xxx-1234567890@g.us', verbose_name='WhatsApp dos Admins'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='group_phones',
            field=models.TextField(blank=True, help_text='IDs dos grupos públicos, um por linha. Receberão notificação SEM dados sensíveis do ganhador (apenas nome). Ex: 120363xxx-1234567890@g.us', verbose_name='WhatsApp dos Grupos Públicos'),
        ),
    ]
