# Generated by Django 4.2.7 on 2025-11-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto'),
    ]

    operations = [
        # Sincronização explícita - garante que o schema está correto
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo acesso'),
        ),
    ]
