# Generated by Django 4.2.7 on 2025-11-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto'),
    ]

    operations = [
        # Esta migration vazia serve para sincronizar o estado do banco
        # com o modelo atual caso haja alguma inconsistência
    ]
