# Generated by Django 4.2.7 on 2025-11-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagetemplate',
            name='delay_seconds',
            field=models.IntegerField(default=0, help_text='Tempo de espera antes de enviar a mensagem (em segundos)', verbose_name='Delay (segundos)'),
        ),
    ]
